const FlavorName = [
  "STRAWBERRY KIWI",
  "CITRUS PUNCH",
  "FRUIT PUNCH (COLOR FREE)",
  "APPLE (COLOR FREE)",
  "BERRY",

  "TANGERINE (COLOR FREE)",
  "CHERRY (COLOR FREE)",
  "ORANGE PINEAPPLE",
  "CRAN-APPLE",
  "ORANGE RASPBERRY (COLOR FREE)",

  "BLUE RASPBERRY",
  "GREEN WATERMELON",
  "STRAWBERRY BANANA",
  "WHITE GRAPE (COLOR FREE)",
  "PEACH MANGO (COLOR FREE)",
];

export default FlavorName;
